name: Build

on:
  push:
  workflow_dispatch:
  create:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt install podman

      - name: Login
        run: |
          podman login -u xtexChooser -p ${{ secrets.OCI_REGISTRY_TOKEN }} source.moe
          podman login -u xtexChooser -p $GITHUB_TOKEN ghcr.io

      - name: Build
        run: |
          podman build -t bird .
          podman tag localhost/bird source.moe/xtex-vnet/bird:dev ghcr.io/xtex-vnet/bird:dev
          podman push source.moe/xtex-vnet/bird:dev
          podman push ghcr.io/xtex-vnet/bird:dev

      - name: Publish
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        run: |
          podman tag localhost/bird source.moe/xtex-vnet/bird:${{ github.ref_name }} ghcr.io/xtex-vnet/bird:${{ github.ref_name }}
          podman push source.moe/xtex-vnet/bird:${{ github.ref_name }}
          podman push ghcr.io/xtex-vnet/bird:${{ github.ref_name }}
          podman tag localhost/bird source.moe/xtex-vnet/bird:latest ghcr.io/xtex-vnet/bird:latest
          podman push source.moe/xtex-vnet/bird:latest
          podman push ghcr.io/xtex-vnet/bird:latest
